### ISSUE TITLE
/system/bin/sh: /system/bin/strpmenu : not executable: 64-bit ELF file

### ISSUE THREAD

**Issue by UltimateSentryTurret** [CRANKV2/CRV2#2]
Hey, just installed this, & noticed as soon as I flash it over magisk & reboot & go to termux & put in the command it does this:  
~ $ su -c strpmenu
/system/bin/sh: /system/bin/strpmenu : not executable: 64-bit ELF File

**Comment by UltimateSentryTurret** [comment]
I remember it was previously able to be on 32bit architecture, cause I remember it working before on the phone I use.

**Comment by CRANKV2** [comment]
Yes, actually it was on 2.4 able to run on 32bit devices.

But as you can see here on our stats:
https://strp.cloud/stats/

There are more 64bit users then 32bit users.

Thats why we decided to remove universal support, because it takes much longer to create or update modules for both arch.

**Comment by willdroidv1** [comment]
Plz bring arm32 back STRPv2.5 isnt available for 32bit. plz add universal arch again, this is the best module for my phone plz plz plz

**Comment by CRANKV2** [comment]
comes back on v3.0

Regards

willdroidv1 ***@***.***> schrieb am Mo., 5. Feb. 2024, 19:57:
